### ISSUE TITLE
merge with https://github.com/dareenzo/pymple

### ISSUE THREAD

**Issue by PauloPhagula** [BernhardPosselt/pymple#1]
Hello @BernhardPosselt,

Just like you I faced the problem with the lack of a simple IOC/DIC in python, and end up coming up with a solution of my own, inspired by Fabien Potenciers [Tweetie](https://github.com/fabpot-graveyard/twitte) and [Pimple](http://pimple.sensiolabs.org) libraries.

I was calling it pymple and just tried publishing it into pypi but found a naming conflict with your library. 

I see your version is all nice, polished and modern but doesn't support python < 3.4. So I'd like to know if there's a possibility of trying to come up a merge of yours and mine to allow that support.

Thanks

**Comment by BernhardPosselt** [comment]
The main reason for the 3.4 requirement is the typings module. If we get rid of the typings module, we can also support older versions. The solution should be to go for stub files, that way we can also support older versions, see http://mypy.readthedocs.io/en/latest/basics.html#library-stubs-and-the-typeshed-repo

BTW: We are speaking about Python 3.x support correct? I'd like to drop down to a maximum of Python 3.2, everything else seems to not be around anymore.

**Comment by BernhardPosselt** [comment]
BTW, before you create a pull request, let's first discuss the API specs (unless you want to completely reuse my code xD). 

As far as I can see our APIs are quite different. I've used Pimple quite extensively and moved away from the "register everything manually by string approach" since it was too error prone and maintenance intensive. I've moved to resolving everything by type like Spring's @Autowired. 

Also your approach seems nice from a syntax view but it's probably impossible to type correctly.

**Comment by PauloPhagula** [comment]
Hello @BernhardPosselt I think you're right about everything. Looking from just the surface looks doable but there are actually indeed so many points that don' match:
- I was actually looking into support 2.7 rather than 3.2. Google app engine standard environment for instance uses 2.7 and that' were I mostly host my code. Plus I normally work with Flask and it doesn't quite love python3+
- API - this is mostly adaptable, but the approach of using introspection to infer type dependencies through the typing package is completely different from the string based keying I'm using.
- In terms of investment, effort and commitment you've put in your lib, making changes is not a small deal as you'd probably break and impact on the systems you've already set up.

So I think that summing this up, we're no go. I'll just rename the package.

Great work anyway, your lib is by far the most modern, clean and polished.Well done
